- .github/workflows/cargo.yml
- .github/workflows/coverage.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- cli/actions.rs
- cli/command.rs
- cli/main.rs
- src/async_ftp/mod.rs
- src/lib.rs
- src/sync_ftp/mod.rs
- src/types.rs
#4  - Add support for active mode
This PR adds support for active mode.
To open a data stream with active mode, we create a tcp listener and send a PORT command to tell the ftp server which ip/port to connect to.
> Add active mode

- CHANGELOG.md
- Cargo.toml
- cli/main.rs
- src/async_ftp/mod.rs
- src/sync_ftp/data_stream.rs
- src/sync_ftp/mod.rs
#5 - Close SSL stream
Fixes errors with certain ftp servers, and possible vulnerability to truncation attack.
Close SSL stream properly for every data channel that was opened. Inspired by a fix made on parent [repo](https://github.com/mattnenterprise/rust-ftp)
> Close ssl stream

- src/async_ftp/mod.rs
- src/sync_ftp/mod.rs
FTP commands and responses end with CRLF, which is logged, resulting in a double line return.
This removes the EOL from message to fix it.
FTP specifies CRLF as the only valid EOL marker. 
We know we use it, so I trimmed the end CRLF in sent commands.
For response, I went for a safer approach in case some server don't use proper CRLF.
Let me know if you have a better idea than "CC OUT" / "CC IN" for control channel in/out !
("CMD"/"RESP", "CC ->"/"CC <-" ...)
> Remove EOL in command channel message logs

- src/async_ftp/mod.rs
- src/command.rs
- src/lib.rs
- src/sync_ftp/mod.rs
- Use an enum `Command` instead of strings for performing commands
> commands as enum

- src/async_ftp/mod.rs
- src/sync_ftp/mod.rs
Fixes #14 
- Implemented implicit ftps
> implicit ftps

- .github/workflows/cargo.yml
- .github/workflows/coverage.yml
- Cargo.toml
- src/async_ftp/mod.rs
- src/sync_ftp/mod.rs
#16 [Feature Request] - support of FTP servers running behind a NAT/proxy
This pull request allows client to work with FTP servers running behind NAT in passive mode.
To enable the workaround call
```rust
ftp_stream.set_nat_workaround(true);
```
> NAT workaround for passive mode

- .github/workflows/cargo.yml
- .github/workflows/coverage.yml
- Cargo.toml
- README.md
- cli/actions.rs
- src/async_ftp/data_stream.rs
- src/async_ftp/mod.rs
- src/async_ftp/tls.rs
- src/async_ftp/tls/native_tls.rs
- src/async_ftp/tls/rustls.rs
- src/lib.rs
- src/list.rs
- src/sync_ftp/data_stream.rs
- src/sync_ftp/mod.rs
- src/sync_ftp/tls.rs
- src/sync_ftp/tls/native_tls.rs
- src/sync_ftp/tls/rustls.rs
> Allow using rustls instead of native-tls

- suppaftp/src/lib.rs
Signed-off-by: Xuanwo <github@xuanwo.io>
TlsConnector is not exported. Makes it impossible to call `into_secure`.
> fix: async TlsConnector not exported

- suppaftp/src/async_ftp/mod.rs
- suppaftp/src/list.rs
- suppaftp/src/sync_ftp/mod.rs
- suppaftp/src/types.rs
Fixes #24
- Don't use read to string from stream, but read line
- Response body is now bytes
> Can't work with some special FTP response

- CHANGELOG.md
- suppaftp/src/list.rs
`suppaftp::list::File` now derives the hash trait. For that also `PosixPex` and `FileType` now derives the hash trait.
That is useful for creating a Hashmap out of the response of `FtpStream::list` call so that the responses can be easily compared / subtracted from each other.
> Derive hash trait for `File` and dependencies

- CHANGELOG.md
- README.md
- suppaftp-cli/Cargo.toml
- suppaftp-cli/src/actions.rs
- suppaftp-cli/src/command.rs
- suppaftp-cli/src/main.rs
- suppaftp/Cargo.toml
- suppaftp/src/async_ftp/mod.rs
- suppaftp/src/command.rs
- suppaftp/src/lib.rs
- suppaftp/src/list.rs
- suppaftp/src/regex.rs
- suppaftp/src/sync_ftp/mod.rs
- suppaftp/src/types.rs
Fixes #28 
Implementation of EPSV according to [RFC 2428, section 3](https://www.rfc-editor.org/rfc/rfc2428#section-3). See also <https://www.jscape.com/blog/what-is-the-ftp/s-epsv-command-and-when-do-you-use-it>
> Implement EPSV (Extended Passive Mode)

- .github/workflows/cargo.yml
- CHANGELOG.md
- README.md
- suppaftp-cli/Cargo.toml
- suppaftp-cli/src/actions.rs
- suppaftp-cli/src/main.rs
- suppaftp/Cargo.toml
- suppaftp/src/async_ftp/data_stream.rs
- suppaftp/src/async_ftp/mod.rs
- suppaftp/src/async_ftp/tls.rs
- suppaftp/src/async_ftp/tls/native_tls.rs
- suppaftp/src/async_ftp/tls/rustls.rs
- suppaftp/src/lib.rs
- suppaftp/src/sync_ftp/data_stream.rs
- suppaftp/src/sync_ftp/mod.rs
- suppaftp/src/sync_ftp/tls.rs
- suppaftp/src/sync_ftp/tls/native_tls.rs
- suppaftp/src/sync_ftp/tls/rustls.rs
Fixes #33
- [Issue 33](https://github.com/veeso/suppaftp/issues/33) **‼️ BREAKING CHANGES ‼️**
- Features are now additive. This means that you can successfully build suppaftp with all the features enabled at the same time.
- Ftp stream has now been split into different types:
- `FtpStream`: sync no-tls stream
- `NativeTlsFtpStream`: ftp stream with TLS with native-tls
- `RustlsFtpStream`: ftp stream with TLS with rustls
- `AsyncFtpStream`: async no-tls stream
- `AsyncNativeTlsFtpStream`: async ftp stream with TLS with async-native-tls
- `AsyncRustlsFtpStream`: async ftp stream with TLS with async-rustls
> 33 bug features are not additive

- CHANGELOG.md
- README.md
- suppaftp/Cargo.toml
- suppaftp/src/async_ftp/mod.rs
- suppaftp/src/lib.rs
- suppaftp/src/sync_ftp/mod.rs
Fixes #37
- Implemented new connection method `connect_timeout` with the possibility to specify a timeout on connect
> connect_timeout

- README.md
Brand new to this crate and was trying the sample code and had an error.
Fixes typo in example code in the README.
```
no method named `put` found for struct `ImplFtpStream`
```
> Fix typo in Readme, put -> put_file

- README.md
Fixes #52 
After digging a little bit, I've found the docs are wrong and this PR fixes it.
> Improve example from async on readme and avoid errors

- suppaftp/Cargo.toml
- suppaftp/src/async_ftp/mod.rs
- suppaftp/src/command.rs
- suppaftp/src/lib.rs
- suppaftp/src/list.rs
- suppaftp/src/sync_ftp/data_stream.rs
- suppaftp/src/sync_ftp/mod.rs
- suppaftp/src/types.rs
#56 - Added doc_cfg where appropriate and silenced warnings when building the docs
Fixes #56 
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
List here your changes
- Added `#[cfg_attr(docsrs, doc(cfg(...)))]` where appropriate in order to properly document conditionally compiled items with `--all-features` (`cargo +nightly rustdoc --all-features --open -- --cfg docsrs`).
- Silenced `warning: unclosed HTML tag DIR` by properly enclosing raw text.
> Added doc_cfg where appropriate and silenced warnings when building the docs

- suppaftp/src/list.rs
Fixes #58 
- Here, I adjust the `POSIX_LS_RE` to account for `s`, `S`, `t`, and `T` in the "pex"-y positions, by adding them to the set of characters we scan for 9 of. Now, the following characters are included in the scan:
`-rwxsStT`, where previously only `-rwxs` were supported. Off-hand, it appears the `s` was an attempt to support setuid/setgid, but it did not cover the case where the `x` bit is _not_ set, which renders as a `S`.
Because this regex did not previously validate for the correct ordering (i.e., refuting strange combos like `rxw`), I did not add them in this PR.
- The `pex` parsing closure, which does some simple arithmetic to determine the "pex" value, needed some updates.
`S` and `T` indicate the presence of a setuid/setgid bit, or a sticky bit, but _without_ `x`. (If …
> Add POSIX setgid/setuid/sticky bit support

- suppaftp/src/async_ftp/mod.rs
- suppaftp/src/sync_ftp/mod.rs
45 - Send + Sync traits to AsyncFtpStream/FtpStream
Fixes #45 
To make AsyncFtpStream/FtpStream Send+Sync, tls_ctx should be declared as Send+Sync. AsyncTlsConnector and TlsConnector already satisfay Send+Sync traits so no breaking change is expected
List here your changes
- `tls_ctx: Option<Box<dyn AsyncTlsConnector<Stream = T>>>` to `tls_ctx: Option<Box<dyn AsyncTlsConnector<Stream = T> + Send + Sync + 'static>`
> feat: Send + Sync trait to AsyncFtpStream/FtpStream

- suppaftp/src/async_ftp/mod.rs
- suppaftp/src/sync_ftp/mod.rs
Fixes #66 
- It was possible to pass a reference to data_stream, instead of ownership, which the code intended.
- Require 'static, ie. normal references cannot be passed anymore.
- Could stop old, buggy code from compiling.
> Fix abort() getting stuck when being passed a reference

- CHANGELOG.md
- suppaftp/src/async_ftp/mod.rs
- suppaftp/src/sync_ftp/mod.rs
Fixes #64
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
List here your changes
- Added timeout argument to active
- timeout for incoming connections
> feat: active mode socket timeout

- README.md
I die
Fixes # Incorrect Async example
Changed the documentation for the Async example on the projects home page, it was using a incorrect import.
- I fixed the AsyncTLS example code
> Fixed async example

- README.md
I think it was using and outdated format.
New: https://github.com/veeso/suppaftp/actions/workflows/cargo.yml/badge.svg
Old: https://github.com/veeso/suppaftp/workflows/Build/badge.svg
The build badge was reporting previous builds as if they were failing. The Actions page says otherwise. With builds being incorrectly reported as failed, it might deter people from using suppaftp.
List here your changes
- Updated the SVG path for the build badge on the projects readme
> fix: Build badge was using an incorrect path resulting in false "failed" status

- CHANGELOG.md
- Cargo.toml
- README.md
- suppaftp/src/list.rs
My Windows FTP server responds to the LIST command with data formatted like this : 
"12-20-22  02:45PM       <DIR>          games"
This causes a date parsing error, According to Microsoft documentations, the standard dateformat should be month-day-year .
Reference : https://learn.microsoft.com/en-us/windows/win32/sysinfo/ms-dos-date-and-time
> fix:ms-dos date format

- .github/workflows/cargo.yml
- .github/workflows/cli.yml
- .github/workflows/coverage.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- suppaftp/Cargo.toml
- suppaftp/src/async_ftp/mod.rs
- suppaftp/src/sync_ftp/mod.rs
- suppaftp/src/sync_ftp/tls/rustls.rs
> Hi, i'm trying to connect to a FTP server over a SOCKS5 proxy. Connecting works fine.
> I just connect with `FtpStream::connect_with_stream(stream.into_inner())?` where `stream` is my SOCKS5 `TcpStream`.
> The problem is now:  In passive mode, when i want to retrieve a file, the connection to the server is not done via the proxy (provided `TcpStream`).
> It instantiates a new `TcpStream` internally.
> Is there a way to achieve connecting over a custom provided `TcpStream` when doing `retr_as_stream`?
> Best regards,
> Mark
The implementation consists in being able to provide a `Fn` to set the `TcpStream` from the `SocketAddr` when passive mode is initialized.
> fix: Passive mode with custom provided TcpStream

- suppaftp/src/sync_ftp/tls/rustls.rs
https://github.com/veeso/suppaftp/issues/95
> fix: close rustls stream on drop

- suppaftp/src/async_ftp/mod.rs
- suppaftp/src/sync_ftp/mod.rs
https://github.com/veeso/suppaftp/issues/88
removed `ip.is_private()` check for NAT workaround
> fix: remove is_private check for nat workaround

- CHANGELOG.md
- CONTRIBUTING.md
Fixes #98  (doc: minor typos in CONTRIBUTING.md reference 'termscp' rather than 'suppaftp')
Minor documentation fixes to the `CONTRIBUTING.md` file.
[checkboxes not relevant for these changes omitted]
> fix: doc: fix minor typos referencing 'termscp' in CONTRIBUTING.md (#98)

- CHANGELOG.md
- Cargo.toml
- README.md
- suppaftp/Cargo.toml
- suppaftp/src/async_ftp/tls/rustls.rs
async-tls is unmaintained and rustls has actually released an official version for async tls, so we should use that instead
fix #100
> feat(deps): migrated from async-tls to futures-rustls

- README.md
- suppaftp/Cargo.toml
- suppaftp/examples/rustls.rs
This is a companion PR to https://github.com/veeso/suppaftp/pull/104, adding the updated rustls example also as an executable example in the codebase (with some added inline docs). I'm providing this as a separate PR in case you don't want to provide any examples like that. :)
While working with suppaftp I was looking for (stand-alone executable) examples but didnt' find any. On the occasion of updating the rustls example I thought it'd be a good occasion to also offer a stand-alone example of it (this also helped me test the code for the README and might help others to do so in the future).
> chore: Add executable rustls example

- .github/workflows/cargo.yml
- CHANGELOG.md
- Cargo.toml
- suppaftp/src/async_ftp/mod.rs
- suppaftp/src/lib.rs
- suppaftp/src/list.rs
- suppaftp/src/sync_ftp/mod.rs
- suppaftp/src/test_container.rs
Changed the logic of get stream lines: use read_until and then convert to UTF8 lossy
closes #106
> fix: Fixed `list` related commands which failed if the file name contained non UTF8 characters

- CHANGELOG.md
- suppaftp/src/async_ftp/mod.rs
- suppaftp/src/command.rs
- suppaftp/src/command/feat.rs
- suppaftp/src/sync_ftp/mod.rs
The parser didn't fully respect the RFC 2389
closes #108
> fix: FEAT command response parser

- CHANGELOG.md
Hi,
I just carefully updated a few dependencies for one of my projects and got surprised that my MSRV guarantee (1.82) was suddenly not upheld anymore, and I tracked it down to suppaftp's 7.0.0 update.
I can only speak for myself but I think it's generally a good idea to mention MSRV bumps in the changelogs, especially when it's a jump that now requires a <6 months old rust version (before: <12 months old) - I'm trying my best to keep system requirements and disruptions to a minimum for people who package my projects, and such a sudden jump is not ideal (I'll probably downgrade suppaftp now and wait a few months, unless there is something super critical that forces an update).
Anyhow, to save others from running into this without warning, I'm proposing a mention in the changelog with this …
> Mention MSRV changes in 7.0.0 changelog entry

- CHANGELOG.md
- Cargo.toml
- README.md
- suppaftp/src/async_ftp.rs
- suppaftp/src/async_ftp/async_std_ftp/data_stream.rs
- suppaftp/src/async_ftp/async_std_ftp/mod.rs
- suppaftp/src/async_ftp/async_std_ftp/tls.rs
- suppaftp/src/async_ftp/async_std_ftp/tls/native_tls.rs
- suppaftp/src/async_ftp/async_std_ftp/tls/rustls.rs
- suppaftp/src/async_ftp/tokio_ftp/data_stream.rs
- suppaftp/src/async_ftp/tokio_ftp/mod.rs
- suppaftp/src/async_ftp/tokio_ftp/tls.rs
- suppaftp/src/async_ftp/tokio_ftp/tls/native_tls.rs
- suppaftp/src/async_ftp/tokio_ftp/tls/rustls.rs
- suppaftp/src/lib.rs
- suppaftp/src/sync_ftp/mod.rs
- suppaftp/src/sync_ftp/tls.rs
`TlsStream` for sync ftp.
`AsyncStdTlsStream` for async-std ftp.
closes #121
> fix: Exported `TlsStream` types for implementing functions that use the retrieved stream.

- CHANGELOG.md
- Cargo.toml
- README.md
- suppaftp/Cargo.toml
`suppaftp` uses `and_utc` method on `NaiveDateTime`, which was only added in [chrono v0.4.25](https://github.com/chronotope/chrono/releases/tag/v0.4.25). Fix dependency version in `Cargo.toml` to ensure that this method is actually present.
> Update chrono version
